### ISSUE TITLE
Providing warning that some commands in README.md are repository name-dependent?

### ISSUE THREAD

**Issue by kwesiRutledge** [MIT-REALM/franka_ros#1]
Thanks for building this again, @dawsonc!

It looks like some commands in this template's README.md file are repository dependent and I was wondering if it would be worth explaining this to users in the `Dockerized Franka ROS Interface` section?

## Background

I'm still working my way through it, but I was having trouble executing:

https://github.com/MIT-REALM/franka_ros/blob/bf44733a7430132a71afe792148e007c24be85b9/README.md?plain=1#L16

and used my weak Docker-fu to realize that the name of the container that I needed to attach to was derived from my repo name (i.e., in my case it was `aclbf-hardware2-main-1`. I know, my name is terrible right now. lol)

Would it make sense to alter some of the instructions that are "repo-dependant" in the README.md? One small suggested change is writing:
```
docker attach <repo_name>-main-1
```
in the README instead of the previous statement, but I'm not sure if there are other parts that would need to be modified.

**Comment by dawsonc** [comment]
Good catch! Would you be able to submit a quick PR editing the readme to be a bit more clear? Thanks!On Oct 10, 2023, at 5:29 PM, Kwesi Rutledge ***@***.***> wrote:﻿
Thanks for building this again, @dawsonc!
It looks like some commands in this template's README.md file are repository dependent and I was wondering if it would be worth explaining this to users in the Dockerized Franka ROS Interface section?
Background
I'm still working my way through it, but I was having trouble executing:
https://github.com/MIT-REALM/franka_ros/blob/bf44733a7430132a71afe792148e007c24be85b9/README.md?plain=1#L16
and used my weak Docker-fu to realize that the name of the container that I needed to attach to was derived from my repo name (i.e., in my case it was aclbf-hardware2-main-1. I know, my name is terrible right now. lol)
Would it make sense to alter some of the instructions that are "repo-dependant" in the README.md? One small suggested change is writing:
docker attach <repo_name>-main-1

in the README instead of the previous statement, but I'm not sure if there are other parts that would need to be modified.

**Comment by kwesiRutledge** [comment]
Thanks! I'll create a PR! I wanted to first attempt as many of the instructions as I could and I think I've covered a lot of them now.
